# Generated by Django 4.1.5 on 2023-06-03 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_blog_users_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_column',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
