# Generated by Django 4.1.5 on 2023-06-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_blog_date_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='users_liked',
        ),
        migrations.AddField(
            model_name='blog',
            name='like_status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
