# Generated by Django 4.1.5 on 2023-06-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_blog_users_liked_blog_like_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like_status',
        ),
        migrations.AddField(
            model_name='blog',
            name='users_liked',
            field=models.ManyToManyField(related_name='liked_categories', to='user.user'),
        ),
    ]
